services:
  mosquitto:
    image: eclipse-mosquitto:2.1-alpine
    container_name: mosquitto
    restart: unless-stopped

    ports:
      - "${MQTT_PORT}:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - influxdb3-data:/var/lib/influxdb3
    command:
      - influxdb3
      - serve
      - --node-id
      - influxdb3
      - --object-store
      - file
      - --data-dir
      - /var/lib/influxdb3
      - --without-auth

volumes:
  mosquitto:
  influxdb3-data: