services:
  mosquitto:
    image: eclipse-mosquitto:2.1-alpine
    container_name: mosquitto
    restart: unless-stopped

    ports:
      - "${MQTT_PORT}:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./influxdb3-data:/var/lib/influxdb3
    command:
      - influxdb3
      - serve
      - --node-id
      - influxdb3
      - --object-store
      - file
      - --data-dir
      - /var/lib/influxdb3
      - --without-auth
      - --query-file-limit
      - "${INFLUXDB_QUERY_FILE_LIMIT:-600}"

  influxdb-init:
    image: curlimages/curl:8.12.1
    depends_on:
      - influxdb3
    environment:
      INFLUXDB_URL: http://influxdb3:8181
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE:-weather-station-db}
      INFLUXDB_RETENTION_PERIOD: ${INFLUXDB_RETENTION_PERIOD:-15d}
    volumes:
      - ./init-influxdb.sh:/scripts/init-influxdb.sh:ro
    entrypoint: ["/bin/sh", "/scripts/init-influxdb.sh"]

volumes:
  mosquitto:
  influxdb3-data:
